dart: [stable]
dist: xenial
language: dart
notifications: {email: false}

install: pub get
before_script: pub global activate coveralls
script: pub run grinder test
after_success: pub global run coveralls var/lcov.info
