dart: [dev, stable]
dist: xenial
language: dart
notifications: {email: false}

install:
  - pub global activate coveralls
  - pub get

script: pub run grinder test
after_success: pub global run coveralls var/lcov.info
